### ISSUE TITLE
[Bug] Components between stacks must be unique to avoid conflicts

### ISSUE THREAD

**Issue by mschlin** [davoodharun/terragrunt-scaffolder#2]
Currently, if I were to have 2 stacks with the same component, and run `tgs generate`, then only 1 of those components will be generated despite potential differences in `source`, `provider`, `version`, and `description`.

Ex: Given:
```
// vanilla.yaml
stack:
  name: vanilla
  version: 1.0.0
  description: foobar
  components:
    serviceplan:
      source: "azurerm_service_plan"
      provider: "azurerm"
      version: "3.0.0"
      description: "Shared service plan for all services"
...

//chocolate.yaml
stack:
  name: chocolate
  version: 1.0.0
  description: foobar
  components:
    serviceplan:
      source: "aws_vpc"
      provider: "aws"
      version: "5.19.0"
      description: "barfoo"
...
```
Run `tgs generate`

**Expected**: 2 `serviceplan` module folders are created in `_components`

**Result**: 1 `serviceplan` module folder is created in `_components` of whichever stack was run later (in this case, `chocolate.yaml`'s `serviceplan` won out)

**Potential Solutions**:
1. Generate component modules with the stack name in mind, for example like `.../_components/{stack_name}/{component_name}`
2. enforce requirement that all stack components must be unique globally (not useful if we want 2+ stacks to have the same component)

**Reasoning**:
While this tool is very helpful and awesome, right now it doesn't have the capability to differentiate between components with the same name across stacks. This can potentially cause issues where a user might generate a stack whose components use the versions/modules/providers of a different stack, leading to unexpected errors.
